export const ADMIN_LINKS = [
  { href: "/dashboard/admin", label: "Resumen" },
  { href: "/dashboard/admin/stats", label: "Stats" },
  { href: "/dashboard/admin/settings", label: "Configuración" },
  { href: "/dashboard/admin/competitions", label: "Competencias" },
  { href: "/dashboard/admin/world-cup-groups", label: "Estructura · Tablas/Grupos" },
  { href: "/dashboard/admin/world-cup-bracket", label: "Estructura · Playoffs" },
  { href: "/dashboard/admin/quiniela-plus", label: "Quiniela +" },
  { href: "/dashboard/admin/prizes", label: "Premios" },
  { href: "/dashboard/admin/users", label: "Usuarios" },
  { href: "/dashboard/admin/picks", label: "Picks" },
  { href: "/dashboard/admin/survivor", label: "Survivor" },
  { href: "/dashboard/admin/vip", label: "VIP" },
  { href: "/dashboard/admin/user-info", label: "Info usuarios" },
  { href: "/dashboard/admin/final-ranking", label: "Ranking final" },
  { href: "/dashboard/admin/payments", label: "Pagos" },
  { href: "/dashboard/admin/seasons", label: "Temporadas" },
  { href: "/dashboard/admin/matchdays", label: "Jornadas" },
  { href: "/dashboard/admin/odds", label: "Probabilidades" },
  { href: "/dashboard/admin/matches", label: "Partidos" },
  { href: "/dashboard/admin/nfl-lines", label: "NFL · Líneas" },
  { href: "/dashboard/admin/results", label: "Resultados" },
  { href: "/dashboard/admin/live-score", label: "Live Score" },
  { href: "/dashboard/admin/hall-of-fame", label: "Salón de la Fama" },
  { href: "/dashboard/admin/trophies", label: "Trofeos" },
  { href: "/dashboard/admin/rules", label: "Reglamento" },
  { href: "/dashboard/admin/teams", label: "Equipos" },
] as const;
