from __future__ import annotations

import re
import unicodedata
from datetime import datetime

from app.core.datetime import MEXICO_CITY_TZ, ensure_utc
from app.models.entities import Team

TEAM_CODE_ALIASES = {
    "club america": "AME",
    "america": "AME",
    "cf america": "AME",
    "guadalajara": "GDL",
    "chivas": "GDL",
    "guadalajara chivas": "GDL",
    "cd guadalajara": "GDL",
    "cruz azul": "CAZ",
    "pumas unam": "PUM",
    "u.n.a.m. - pumas": "PUM",
    "u.n.a.m.": "PUM",
    "unam": "PUM",
    "pumas": "PUM",
    "toluca": "TOL",
    "monterrey": "MTY",
    "rayados": "MTY",
    "cf monterrey": "MTY",
    "tigres uanl": "TIG",
    "u.a.n.l. - tigres": "TIG",
    "tigres": "TIG",
    "pachuca": "PAC",
    "leon": "LEO",
    "santos laguna": "SAN",
    "santos": "SAN",
    "atlas": "ATL",
    "queretaro": "QRO",
    "queretaro fc": "QRO",
    "necaxa": "NEC",
    "puebla": "PUE",
    "mazatlan fc": "MAZ",
    "mazatlan": "MAZ",
    "fc juarez": "JUA",
    "juarez": "JUA",
    "bravos": "JUA",
    "club tijuana": "TIJ",
    "tijuana": "TIJ",
    "xolos": "TIJ",
    "atletico san luis": "ASL",
    "atletico de san luis": "ASL",
    "san luis": "ASL",
    "albania": "ALB",
    "argelia": "ALG",
    "algeria": "ALG",
    "argentina": "ARG",
    "australia": "AUS",
    "austria": "AUT",
    "belgica": "BEL",
    "belgium": "BEL",
    "bolivia": "BOL",
    "bosnia": "BIH",
    "bosnia and herzegovina": "BIH",
    "bosnia herzegovina": "BIH",
    "bosnia & herzegovina": "BIH",
    "brasil": "BRA",
    "brazil": "BRA",
    "cabo verde": "CPV",
    "cape verde": "CPV",
    "cameroon": "CMR",
    "camerun": "CMR",
    "canada": "CAN",
    "chile": "CHI",
    "china": "CHN",
    "colombia": "COL",
    "corea del sur": "KOR",
    "corea republica": "KOR",
    "korea republic": "KOR",
    "south korea": "KOR",
    "costa de marfil": "CIV",
    "cote d ivoire": "CIV",
    "cote divoire": "CIV",
    "ivory coast": "CIV",
    "costa rica": "CRC",
    "croacia": "CRO",
    "croatia": "CRO",
    "curacao": "CUW",
    "curazao": "CUW",
    "dinamarca": "DEN",
    "denmark": "DEN",
    "ecuador": "ECU",
    "egipto": "EGY",
    "egypt": "EGY",
    "el salvador": "SLV",
    "emiratos arabes unidos": "UAE",
    "united arab emirates": "UAE",
    "england": "ENG",
    "inglaterra": "ENG",
    "espana": "ESP",
    "spain": "ESP",
    "estados unidos": "USA",
    "united states": "USA",
    "united states of america": "USA",
    "usa": "USA",
    "francia": "FRA",
    "france": "FRA",
    "gales": "WAL",
    "wales": "WAL",
    "ghana": "GHA",
    "haiti": "HAI",
    "alemania": "GER",
    "germany": "GER",
    "deutschland": "GER",
    "greece": "GRE",
    "grecia": "GRE",
    "guatemala": "GUA",
    "honduras": "HON",
    "iran": "IRN",
    "irlanda": "IRL",
    "republica de irlanda": "IRL",
    "republic of ireland": "IRL",
    "iraq": "IRQ",
    "irak": "IRQ",
    "italia": "ITA",
    "italy": "ITA",
    "jamaica": "JAM",
    "japon": "JPN",
    "japan": "JPN",
    "jordania": "JOR",
    "jordan": "JOR",
    "mali": "MLI",
    "marruecos": "MAR",
    "morocco": "MAR",
    "mexico": "MEX",
    "mejico": "MEX",
    "new zealand": "NZL",
    "nigeria": "NGA",
    "noruega": "NOR",
    "norway": "NOR",
    "nueva zelanda": "NZL",
    "paises bajos": "NED",
    "netherlands": "NED",
    "holland": "NED",
    "panama": "PAN",
    "paraguay": "PAR",
    "peru": "PER",
    "poland": "POL",
    "polonia": "POL",
    "portugal": "POR",
    "qatar": "QAT",
    "republica checa": "CZE",
    "czech republic": "CZE",
    "czechia": "CZE",
    "rd congo": "COD",
    "dr congo": "COD",
    "congo dr": "COD",
    "republica democratica del congo": "COD",
    "democratic republic of the congo": "COD",
    "rumania": "ROU",
    "romania": "ROU",
    "arabia saudita": "KSA",
    "saudi arabia": "KSA",
    "scotland": "SCO",
    "escocia": "SCO",
    "senegal": "SEN",
    "serbia": "SRB",
    "slovakia": "SVK",
    "eslovaquia": "SVK",
    "slovenia": "SVN",
    "eslovenia": "SVN",
    "south africa": "RSA",
    "sudafrica": "RSA",
    "suecia": "SWE",
    "sweden": "SWE",
    "suiza": "SUI",
    "switzerland": "SUI",
    "tunez": "TUN",
    "tunisia": "TUN",
    "turkiye": "TUR",
    "turkey": "TUR",
    "turquia": "TUR",
    "ukraine": "UKR",
    "ucrania": "UKR",
    "uruguay": "URU",
    "uzbekistan": "UZB",
    "venezuela": "VEN",
}

EQUIVALENT_TEAM_CODES = {
    "GDL": ("GDL", "CHI"),
    "CHI": ("CHI", "GDL"),
    "ASL": ("ASL", "SLP"),
    "SLP": ("SLP", "ASL"),
    "ATL": ("ATL", "ATLX"),
    "ATLX": ("ATLX", "ATL"),
    "ALG": ("ALG", "DZA"),
    "DZA": ("DZA", "ALG"),
    "BIH": ("BIH", "BOS"),
    "BOS": ("BOS", "BIH"),
    "CHI": ("CHI", "CHL"),
    "CHL": ("CHL", "CHI"),
    "COD": ("COD", "DRC"),
    "DRC": ("DRC", "COD"),
    "CRC": ("CRC", "COS"),
    "COS": ("COS", "CRC"),
    "CUW": ("CUW", "CUR"),
    "CUR": ("CUR", "CUW"),
    "CZE": ("CZE", "CZH"),
    "CZH": ("CZH", "CZE"),
    "DEN": ("DEN", "DIN"),
    "DIN": ("DIN", "DEN"),
    "ECU": ("ECU", "EQU"),
    "EQU": ("EQU", "ECU"),
    "EGY": ("EGY", "EGI"),
    "EGI": ("EGI", "EGY"),
    "ENG": ("ENG", "ING"),
    "ING": ("ING", "ENG"),
    "ESP": ("ESP", "SPA"),
    "SPA": ("SPA", "ESP"),
    "GER": ("GER", "DEU", "ALE"),
    "DEU": ("DEU", "GER", "ALE"),
    "ALE": ("ALE", "GER", "DEU"),
    "GRE": ("GRE", "GRC"),
    "GRC": ("GRC", "GRE"),
    "HAI": ("HAI", "HTI"),
    "HTI": ("HTI", "HAI"),
    "IRN": ("IRN", "IRA"),
    "IRA": ("IRA", "IRN"),
    "KOR": ("KOR", "COR"),
    "COR": ("COR", "KOR"),
    "KSA": ("KSA", "SAU"),
    "SAU": ("SAU", "KSA"),
    "MAR": ("MAR", "MOR"),
    "MOR": ("MOR", "MAR"),
    "MEX": ("MEX", "MX"),
    "MX": ("MX", "MEX"),
    "NED": ("NED", "HOL"),
    "HOL": ("HOL", "NED"),
    "NZL": ("NZL", "NZ"),
    "NZ": ("NZ", "NZL"),
    "PAR": ("PAR", "PRY"),
    "PRY": ("PRY", "PAR"),
    "POR": ("POR", "PRT"),
    "PRT": ("PRT", "POR"),
    "ROU": ("ROU", "ROM"),
    "ROM": ("ROM", "ROU"),
    "RSA": ("RSA", "ZAF", "SAF"),
    "ZAF": ("ZAF", "RSA", "SAF"),
    "SAF": ("SAF", "RSA", "ZAF"),
    "SUI": ("SUI", "SWI"),
    "SWI": ("SWI", "SUI"),
    "TUR": ("TUR", "TURK"),
    "TURK": ("TURK", "TUR"),
    "UAE": ("UAE", "ARE"),
    "ARE": ("ARE", "UAE"),
    "USA": ("USA", "US"),
    "US": ("US", "USA"),
    "URU": ("URU", "URY"),
    "URY": ("URY", "URU"),
}


def normalize_text(value: str | None) -> str:
    normalized = unicodedata.normalize("NFKD", (value or "").strip().lower())
    ascii_only = normalized.encode("ascii", "ignore").decode("ascii")
    compact = re.sub(r"[^a-z0-9]+", " ", ascii_only)
    return " ".join(compact.split())


def team_lookup_keys(team: Team) -> list[str]:
    return [
        normalize_text(team.short_name),
        normalize_text(team.name),
        normalize_text(team.slug),
    ]


def build_team_code_lookup(teams: list[Team]) -> dict[str, str]:
    lookup: dict[str, str] = {}
    for team in teams:
        code = team.short_name.upper()
        for key in team_lookup_keys(team):
            if key:
                lookup[key] = code
    for alias, code in TEAM_CODE_ALIASES.items():
        lookup.setdefault(normalize_text(alias), code)
    return lookup


def resolve_team_code(
    value: str | None,
    lookup: dict[str, str],
    actual_codes: set[str] | None = None,
) -> str | None:
    key = normalize_text(value)
    if not key:
        return None
    code = lookup.get(key)
    if code is None:
        return None

    available_codes = actual_codes or set(lookup.values())
    for candidate in EQUIVALENT_TEAM_CODES.get(code, (code,)):
        if candidate in available_codes:
            return candidate
    return code


def mexico_city_match_date(value: datetime) -> str:
    return ensure_utc(value).astimezone(MEXICO_CITY_TZ).date().isoformat()
